# hugo.toml

theme = "hugo-book" 

baseURL = "/" 
languageCode = "zh-cn" 
languageLang = "zh-cn"
title = "我的 Wiki 文档站" 

# RSS, categories and tags disabled for an easy start
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
  # 啟用自動深色模式和切換按鈕
  enableDarkMode = true 
  
  images = ["img/og-image.jpg"]

  # Book Theme 的其他參數（可選）
  BookPortableLinks = true